# Generated by Django 4.2.7 on 2025-04-05 22:20

from django.db import migrations, models
import tests_psicologicos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstruccionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_test', models.CharField(max_length=20, unique=True)),
                ('texto_instrucciones', models.TextField()),
                ('ejemplo_pregunta', models.TextField()),
                ('ejemplo_opcion_a', models.CharField(max_length=255)),
                ('ejemplo_opcion_b', models.CharField(max_length=255)),
                ('ejemplo_opcion_c', models.CharField(max_length=255)),
                ('ejemplo_opcion_d', models.CharField(max_length=255)),
                ('respuesta_correcta', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaWonderlic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField()),
                ('opcion_a', models.CharField(max_length=255)),
                ('opcion_b', models.CharField(max_length=255)),
                ('opcion_c', models.CharField(max_length=255)),
                ('opcion_d', models.CharField(max_length=255)),
                ('respuesta_correcta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SesionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(choices=[('wonderlic', 'Wonderlic'), ('ic', 'IC'), ('bip', 'BIP'), ('disc', 'DISC'), ('kostick', 'Kostick'), ('tecnica', 'Técnica'), ('raven', 'Raven'), ('ipv', 'IPV')], max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('codigo_unico', models.CharField(default=tests_psicologicos.models.generar_codigo, max_length=12, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10, null=True)),
                ('profesion', models.CharField(blank=True, max_length=255, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('puntaje', models.IntegerField(blank=True, null=True)),
                ('potencial', models.CharField(blank=True, choices=[('MUY INFERIOR', 'MUY INFERIOR'), ('INFERIOR', 'INFERIOR'), ('INFERIOR AL T.M.', 'INFERIOR AL T.M.'), ('TERMINO MEDIO', 'TERMINO MEDIO'), ('SUPERIOR AL T.M.', 'SUPERIOR AL T.M.'), ('SUPERIOR', 'SUPERIOR')], max_length=50, null=True)),
                ('puntajes_ipv', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestPsicologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_test', models.CharField(choices=[('wonderlic', 'Wonderlic'), ('ic', 'IC'), ('bip', 'BIP'), ('disc', 'DISC'), ('kostick', 'Kostick'), ('tecnica', 'Técnica'), ('raven', 'Raven'), ('ipv', 'IPV')], max_length=20)),
                ('texto_pregunta', models.TextField()),
                ('opcion_a', models.CharField(max_length=255)),
                ('opcion_b', models.CharField(max_length=255)),
                ('opcion_c', models.CharField(blank=True, max_length=255, null=True)),
                ('opcion_d', models.CharField(blank=True, max_length=255, null=True)),
                ('opcion_e', models.CharField(blank=True, max_length=255, null=True)),
                ('opcion_f', models.CharField(blank=True, max_length=255, null=True)),
                ('respuesta_correcta', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
